### ISSUE TITLE
Error while getting latest block

### ISSUE THREAD

**Issue by rsnpj** [icon-project/icon-sdk-js#44]
Implementation:
```
module.exports.getLatestBlock = async () => {
    return new Promise(async (resolve, reject) => {
        try {
            let block = await iconService.getLastBlock().execute();
            resolve(block);
        }
        catch (e) {
            console.log(e)
            reject({ msg: 'Invalid' });
        }
    })
}
```

Error:
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at t.XMLHttpRequest.open (E:\workspace\node.websocket-service\node_modules\icon-sdk-js\build\icon-sdk-j    at t.default.<anonymous> (E:\workspace\node.websocket-service\node_modules\icon-sdk-js\build\icon-sdk-js.node.min.js:39:104093)
    at Generator.next (<anonymous>)
    at E:\workspace\node.websocket-service\node_modules\icon-sdk-js\build\icon-sdk-js.node.min.js:18:1616      at new Promise (<anonymous>)
    at Module.d (E:\workspace\node.websocket-service\node_modules\icon-sdk-js\build\icon-sdk-js.node.min.js:18:1361)
{ msg: 'Invalid' }
```

**Comment by rsnpj** [comment]
Resolved: Typo on the wallet URL.
